version: 2
jobs:
  build:
    docker:
      - image: kroniak/ssh-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8c:a4:dd:2c:47:4c:63:aa:90:0b:e0:d6:15:be:87:82"
      - checkout
      - run:
          name: "Install Git"
          command: |
            apk update
            apk add git
      - run:
          name: "Bootstrap the build"
          command: |
            # Get the latest commit hash
            latest_commit=$(git rev-parse HEAD)
            echo "Latest commit: $latest_commit"
            
            # Get the list of changed files in the latest commit
            changed_files=$(git diff-tree --no-commit-id --name-only -r "$latest_commit")
            echo "Changed files:"
            echo "$changed_files"
            exit 2
            ssh -o StrictHostKeyChecking=no $GPS_BUILD_USER@$GPS_BUILD_SERVER "$GPS_BUILD_BOOTSTRAP"
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: master
